export const GET_STADIUMS_DETAILS_SUCCESS = "GET_STADIUMS_DETAILS_SUCCESS";
export const GET_STADIUMS_DETAILS_ERROR = "GET_STADIUMS_DETAILS_ERROR";
export const CLEAR_STADIUM_DETAILS = "CLEAR_STADIUM_DETAILS";
